### ISSUE TITLE
Runtime error: MPS Unsupported Border padding mode

### ISSUE THREAD

**Issue by tamler** [dajes/frame-interpolation-pytorch#4]
Seems we need relative paths for our Mac users?
The trace back near the bottom mentions C:\Users\Danylo\…

Error using comfyUI on a Mac:

!!! Exception during processing !!!
Traceback (most recent call last):
File "/Users/NAME/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/NAME/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/NAME/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/NAME/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/film/init.py", line 88, in vfi
relust = inference(model, frame_0, frame_1, multiplier - 1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/NAME/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/film/init.py", line 36, in inference
prediction = model(x0, x1, dt)
^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Caskroom/miniconda/base/envs/ComfyUI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/homebrew/Caskroom/miniconda/base/envs/ComfyUI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
File "code/torch/interpolator.py", line 15, in forward
x1: Tensor,
batch_dt: Tensor) -> Tensor:
_0 = (self).debug_forward(x0, x1, batch_dt, )
~~~~~~~~~~~~~~~~~~~ <--- HERE
return (_0["image"])[0]
def debug_forward(self: torch.interpolator.Interpolator,
File "code/torch/interpolator.py", line 29, in debug_forward
feature_pyramids = [_2, _3]
predict_flow = self.predict_flow
forward_residual_flow_pyramid = (predict_flow).forward(feature_pyramids[0], feature_pyramids[1], )
~~~~~~~~~~~~~~~~~~~~~ <--- HERE
predict_flow0 = self.predict_flow
backward_residual_flow_pyramid = (predict_flow0).forward(feature_pyramids[1], feature_pyramids[0], )
File "code/torch/pyramid_flow_estimator.py", line 24, in forward
level_size = torch.slice(torch.size(feature_pyramid_a[i]), 2, 4)
v1 = _0(torch.mul(v0, 2), level_size, None, "bilinear", None, None, False, )
warped = torch.util.warp(feature_pyramid_b[i], v1, )
~~~~~~~~~~~~~~~~~~~ <--- HERE
_predictor0 = self._predictor
v_residual = (_predictor0).forward(feature_pyramid_a[i], warped, )
File "code/torch/util.py", line 78, in warp
_31 = torch.sub(torch.unsqueeze(_30, 2), torch.select(normalized_flow2, -1, 0))
normalized_flow20 = torch.stack([_28, _31], 3)
warped = _20(image, normalized_flow20, "bilinear", "border", False, )
~~~ <--- HERE
_32 = torch.reshape(warped, torch.size(image))
return _32
File "code/torch/torch/nn/functional.py", line 83, in grid_sample
else:
align_corners0 = unchecked_cast(bool, align_corners)
_12 = torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners0)
~~~~~~~~~~~~~~~~~~ <--- HERE
return _12

Traceback of TorchScript, original code (most recent call last):
File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 160, in forward
@torch.jit.export
def forward(self, x0, x1, batch_dt) -> torch.Tensor:
return self.debug_forward(x0, x1, batch_dt)['image'][0]
~~~~~~~~~~~~~~~~~~ <--- HERE
File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 109, in debug_forward

    # Predict forward flow.
    forward_residual_flow_pyramid = self.predict_flow(feature_pyramids[0], feature_pyramids[1])
                                    ~~~~~~~~~~~~~~~~~ <--- HERE

    # Predict backward flow.
File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\util.py", line 85, in warp
], dim=3)

warped = F.grid_sample(image, normalized_flow2,
         ~~~~~~~~~~~~~ <--- HERE
                       mode='bilinear', padding_mode='border', align_corners=False)
return warped.reshape(image.shape)
File "C:\Users\Danylo\anaconda3\envs\research\lib\site-packages\torch\nn\functional.py", line 4223, in grid_sample
align_corners = False

return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
       ~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: MPS: Unsupported Border padding mode

**Comment by eisneim** [comment]
## this is my solution:
change util.py change *padding_mode='border'* to *zeros*
```
    warped = F.grid_sample(image, normalized_flow2, mode='bilinear', 
        padding_mode='zeros', align_corners=False)
        # mode='bilinear', padding_mode='border', align_corners=False)
```
then we need to re-export the jit model

``` python
from interpolator import Interpolator
interpolator = Interpolator()
interpolator.eval()

film_model_path = "/original model weights/film_net_fp32.pt"
film_model = torch.jit.load(film_model_path, map_location='cpu')
film_model.eval()
film_model.float()
film_model = film_model.to(DEVICE)

interpolator.load_state_dict(film_model.state_dict())

interpolatorJit = torch.jit.script(interpolator)
interpolatorJit.save("/Users/teli/www/ml/frame_interpolation/frame-interpolation-pytorch-main/pretrained/film_fp32.pt")

interpolatorfp16 = torch.jit.script(interpolator.half())
interpolatorfp16.save("/Users/teli/www/ml/frame_interpolation/frame-interpolation-pytorch-main/pretrained/film_fp16.pt")
```

from now on you can use the new model weights on mac
```
film_model = torch.jit.load("the exported model weight.pt", map_location='cpu')
```

**Comment by bijlevel** [comment]
Can someone explain to me how to fix this issue. I have adjusted the film_arch.py file, but apparantly I need also to change util.py in a 'frame-interpolation-pytorch' folder. But nowhere on my Mac I can find such a folder & file! Please help! (BTW the code adjustment in rife_arch.py was succesfull, so no errors anymore when using that node, but the quality of interpolation is not so good.)

**Comment by jkawamoto** [comment]
I encountered the same issue, but the patch in https://github.com/dajes/frame-interpolation-pytorch/pull/6 fixes it.

I have re-exported the models and pushed them to https://huggingface.co/jkawamoto/frame-interpolation-pytorch

**Comment by pkyme** [comment]
For some reason this fix isn't working for me - the call to torch.nn.functional.grid_sample in util.warp returns an incorrect result when running with the mps backend. This is with an M4 Pro, it works fine when running on the cpu. I've tried with pytorch nightlies but get the same result.

Temporary workaround is to update util.warp to run grid_sample on the cpu then switch back to mps, but obviously that's not great for performance.
